TICKETMASTER_API_KEY = "YOUR_API_KEY_HERE"
SUPABASE_URL = "https://ujrublkoqtpijwijklvq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqcnVibGtvcXRwaWp3aWprbHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MjEwNzksImV4cCI6MjA5NTk5NzA3OX0.QjXxDHkChXuaDugnwa7zDb8Uepel3w8bm1XorQM1z1g"
EVENTBRITE_PRIVATE_TOKEN = "74PXCQPGK6GLGZOY2B"
SKIDDLE_API_KEY = "be090fa9c35a3542f01517a9966b5ccb"
RESEND_API_KEY = "re_46JYJmgh_NcVKj14t81o7NtvJ8YuBjiKm"
NH_API_KEY = "50239a0a401e4430853960278d32c00c"
